/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description サーバーの稼働状態とタイムスタンプを返却します
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 在庫アイテム一覧取得 */
        get: operations["getStocks"];
        put?: never;
        /** 在庫アイテム新規登録 */
        post: operations["createStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 買い物リスト取得 */
        get: operations["getShoppingList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/expiring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 期限切れ・間近アイテム取得 */
        get: operations["getExpiringItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 在庫アイテム詳細取得 */
        get: operations["getStockById"];
        /** 在庫アイテム更新（楽観的排他制御） */
        put: operations["updateStock"];
        post?: never;
        /** 在庫アイテム削除 */
        delete: operations["deleteStock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{id}/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在庫消費（数量減算） */
        post: operations["consumeStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在ログイン中のユーザー情報取得
         * @description 現在ログインしているユーザー、所属世帯、ロール情報を取得します。未認証時は 401 を返却します。
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/households/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 所属世帯メンバー一覧取得
         * @description ログイン中ユーザーの世帯メンバー一覧を取得します。
         */
        get: operations["getMembers"];
        put?: never;
        /**
         * 家族メンバー招待
         * @description 指定したGoogleメールアドレスを所属世帯に招待します。
         */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /** @example UP */
            status: string;
            /** @example MyHomeStock Backend */
            service: string;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description 在庫管理タイプ (QUANTITY: 個数管理, REMAINING_LEVEL: 4段階残量管理)
         * @example QUANTITY
         * @enum {string}
         */
        StockType: "QUANTITY" | "REMAINING_LEVEL";
        /**
         * @description 4段階残量レベル (EMPTY: すっからかん, LOW: 怪しい, PLENTY: まだまだ, FULL: 十分)
         * @example FULL
         * @enum {string}
         */
        RemainingLevel: "EMPTY" | "LOW" | "PLENTY" | "FULL";
        StockItemRequestDto: {
            /** @example 牛乳 */
            name: string;
            /** @example 冷蔵食品 */
            category?: string;
            /** @example 2 */
            quantity: number;
            /** @example 本 */
            unit?: string;
            /** @example 1 */
            minThreshold: number;
            /** @example 低脂肪乳 */
            memo?: string;
            /**
             * Format: date
             * @example 2026-09-30
             */
            expiryDate?: string;
            stockType?: components["schemas"]["StockType"];
            remainingLevel?: components["schemas"]["RemainingLevel"];
            /**
             * Format: int64
             * @example 0
             */
            version?: number;
            /** @example default */
            householdId?: string;
        };
        StockItemResponseDto: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /** @example default */
            householdId?: string;
            /** @example 牛乳 */
            name: string;
            /** @example 冷蔵食品 */
            category: string;
            /** @example 2 */
            quantity: number;
            /** @example 本 */
            unit: string;
            /** @example 1 */
            minThreshold: number;
            memo?: string;
            /** Format: date */
            expiryDate?: string;
            stockType: components["schemas"]["StockType"];
            remainingLevel?: components["schemas"]["RemainingLevel"];
            /**
             * Format: int64
             * @example 0
             */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AuthUserResponseDto: {
            /**
             * Format: int64
             * @example 1
             */
            userId: number;
            /** @example user@gmail.com */
            email: string;
            /** @example 山田 太郎 */
            displayName?: string;
            pictureUrl?: string;
            /**
             * Format: int64
             * @example 1
             */
            householdId?: number;
            /** @example マイホーム */
            householdName?: string;
            /** @example OWNER */
            role?: string;
        };
        HouseholdMemberRequestDto: {
            /** @example family@gmail.com */
            email: string;
            /** @example MEMBER */
            role?: string;
        };
        HouseholdMemberResponseDto: {
            /**
             * Format: int64
             * @example 1
             */
            id: number;
            /**
             * Format: int64
             * @example 1
             */
            householdId: number;
            /**
             * Format: int64
             * @example 2
             */
            userId?: number;
            /** @example family@gmail.com */
            email: string;
            /** @example 山田 花子 */
            displayName?: string;
            /** @example MEMBER */
            role: string;
            /** @example JOINED */
            status: string;
            /** Format: date-time */
            joinedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    getStocks: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"][];
                };
            };
        };
    };
    createStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockItemRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"];
                };
            };
        };
    };
    getShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"][];
                };
            };
        };
    };
    getExpiringItems: {
        parameters: {
            query?: {
                daysAhead?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"][];
                };
            };
        };
    };
    getStockById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"];
                };
            };
        };
    };
    updateStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockItemRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"];
                };
            };
            /** @description Optimistic Locking Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    consumeStock: {
        parameters: {
            query?: {
                amount?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseDto"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdMemberResponseDto"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseholdMemberRequestDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseholdMemberResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}

export type StockItem = components['schemas']['StockItemResponseDto'];
export type StockItemInput = components['schemas']['StockItemRequestDto'];
export type StockType = components['schemas']['StockType'];
export type RemainingLevel = components['schemas']['RemainingLevel'];
export type HealthResponse = components['schemas']['HealthResponseDto'];
export type AuthUser = components['schemas']['AuthUserResponseDto'];
export type HouseholdMember = components['schemas']['HouseholdMemberResponseDto'];
export type HouseholdMemberInput = components['schemas']['HouseholdMemberRequestDto'];
